prefix :       <http://example.org/>
prefix schema: <http://schema.org/>
prefix dbr:    <http://dbpedia.org/resource/>  


SELECT ?nombreLocalidad (COUNT(?nombreLocalidad) AS ?cuentaLocalidades)
WHERE {
  ?organization a schema:Organization ;
               schema:status "ALTA" ;
               schema:address ?address .
  ?address a schema:PostalAddress ;
           schema:addressLocality ?nombreLocalidad .
}
GROUP BY ?nombreLocalidad
ORDER BY DESC(?cuentaLocalidades)